/// Flutter icons Nutrition
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Nutrition
///      fonts:
///       - asset: fonts/Nutrition.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Nutrition {
  Nutrition._();

  static const _kFontFam = 'Nutrition';
  static const _kFontPkg = null;

  static const IconData barley = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bread_slice = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food_steak = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spoon_sugar = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
